### ISSUE TITLE
STSService.wsdl xml Schema bug

### ISSUE THREAD

**Issue by altinsoft** [vmware/vsphere-automation-sdk-java#171] opened 2022-11-09 10:42 UTC
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [x] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- SDK version:  lastest

- Java version:

- vSphere version: 7

## Expected behavior

Hi,

Vcenter version : 7 or 8

Vmware tool Running, version : 12320

Vm GuestOS : Windows Server 2022

 

With the SAML token that I received through the STSService service We use the StartProgramInGuest function.

But there is an error in the vmware tools VGAuthService service log records.

`[2022-11-09T10:29:27.536Z] [ message] [VGAuthService] requestType: 10(VALIDATE_SAML_BEARER_TOKEN REQ)
[2022-11-09T10:29:27.536Z] [ message] [VGAuthService] username 'Administrator'
[2022-11-09T10:29:27.536Z] [ message] [VGAuthService] validate Only 'FALSE'
[2022-11-09T10:29:27.536Z] [ warning] [VGAuthService] XML Error: Element '{urn:oasis:names:tc:SAML:2.0:assertion}Condition', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value '{http://www.rsa.com/names/2009/12/std-ext/SAML2.0}RenewRestrictionType' of the xsi:type attribute does not resolve to a type definition.
[2022-11-09T10:29:27.536Z] [ warning] [VGAuthService] XML Error: Element '{urn:oasis:names:tc:SAML:2.0:assertion}Condition': The type definition is abstract.
[2022-11-09T10:29:27.536Z] [ warning] [VGAuthService] Failed to validate token against schema
[2022-11-09T10:29:27.536Z] [ message] [VGAuthService] Returning error message '<?xml version="1.0" encoding="UTF-8" ?><reply><sequenceNumber>1</sequenceNumber><errorCode>12</errorCode><errorMsg>validateSamlToken failed</errorMsg></reply>'
[2022-11-09T10:29:27.536Z] [ message] [VGAuthService] ServiceProtoDispatchRequest: processed reqType 10(VALIDATE_SAML_BEARER_TOKEN REQ), returning 0 on connection 3`

Because,

http://www.rsa.com/names/2009/12/std-ext/SAML2.0

no access to the website. The file has been removed.

How can I solve this problem? Can you please help?

![resim](https://user-images.githubusercontent.com/31034706/200809227-d5646409-7972-4e53-8a64-8771d27f55a8.png)

**Comment by kunal-pmj** [comment] 2022-11-10 05:28
Hi @altinsoft 

Providing support for SOAP APIs or the VMWare Tools  is out of scope of this SDK. 
Kindly open a SR against VMWare Tools to engage VMWare Support.

**Closed by kunal-pmj** 2022-11-10 05:28 UTC

**Comment by altinsoft** [comment] 2022-11-10 06:53
> Hi @altinsoft
> 
> Providing support for SOAP APIs or the VMWare Tools is out of scope of this SDK. Kindly open a SR against VMWare Tools to engage VMWare Support.

The problem is not with VMWare Tools, is it? It's a problem with java sdk. Also, where do I get support? I do not have a paid membership.

**Comment by kunal-pmj** [comment] 2022-11-10 09:19
Hi @altinsoft 

Which Java SDK you believe has the issue? 
Also, http://www.rsa.com/names/2009/12/std-ext/SAML2.0 is namespace, a URI not URL. It need not be a resource in the internet.

**Comment by mtsvetanov** [comment] 2022-11-14 11:21
The issue is further discussed here: https://github.com/vmware/open-vm-tools/issues/623
