### ISSUE TITLE
ConnectedAccounts.get() API is broken on VMC

### ISSUE THREAD

**Issue by datvmc** [vmware/vsphere-automation-sdk-java#70] opened 2019-07-24 06:34 UTC
- [Yes ] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [N/A] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [ Yes] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Description
The following code which has been working fine for several months is failing now:
apiClient = VmcClients.custom()
                .setBaseUrl(VMC_URL)
                .setAuthorizationUrl(CSP_URL)
                .setRefreshToken(this.refreshToken.toCharArray())
                .build();
private ConnectedAccounts connectedAccountsStub = 
                         apiClient.createStub(ConnectedAccounts.class);
List<AwsCustomerConnectedAccount>  connectedAccounts = 
                         connectedAccountsStub.get(orgId, null);

It throws the exception with the following message:
Caused by: com.vmware.vapi.bindings.convert.ConverterException: 
Could not convert field 'updated_by_user_id' of structure 'com.vmware.vmc.model.aws_customer_connected_account'

Getting the connected accounts through the API explorer works fine. So, it seems that the mapping of the output from the server to the 'aws_customer_connected_account' structure fails due to an unexpected type. The following message is also seen on the stack trace:

com.vmware.vapi.bindings.convert.ConverterException: Expected value of class com.vmware.vapi.data.StringValue, found com.vmware.vapi.data.OptionalValue.\n\tat com.vmware.vapi.internal.bindings.convert.impl.ConvertUtil.narrowType(ConvertUtil.java:34)\n\ com.vmware.vapi.internal.bindings.TypeConverterImpl$ValueToJavaVisitor.visit(TypeConverterImpl.java:152)\n\tat com.vmware.vapi.bindings.type.StringType.accept(StringType.java:10)

Debugging this some more, it seems that some of the field definitions may be of issue here:

 private static StructType awsCustomerConnectedAccountInit() {
        FieldNameDetails details = null;
        List<ConstraintValidator> validators = null;
        Map<String, Type> fields = new LinkedHashMap();
        Map<String, FieldNameDetails> fieldNameDetails = new HashMap();
        fields.put("updated", new DateTimeType());
        details = new FieldNameDetails("updated", "updated", "getUpdated", "setUpdated");
        fieldNameDetails.put(details.getCanonicalName(), details);

        fields.put("user_id", new StringType());
        details = new FieldNameDetails("user_id", "userId", "getUserId", "setUserId");
        fieldNameDetails.put(details.getCanonicalName(), details);
        fields.put("updated_by_user_id", new StringType());
        details = new FieldNameDetails("updated_by_user_id", "updatedByUserId", "getUpdatedByUserId", "setUpdatedByUserId");

'updated_by_user_id' is defined as a StringType here, but server appears to send a OptionalType?

We are currently blocked on this issue.

## Environment
- SDK version:
The latest libraries as of today.

- Java version: 1.8

**Comment by dhci** [comment] 2019-07-24 09:14
We are hitting the same issue with vmc-bindings-1.9.0.jar.

It appears that client java libraries treat AwsCustomerConnectedAccount.updated_by_user_id and AwsCustomerConnectedAccount.updated as required strings while the server is now sending them as optional type (and null values), so we are getting a vapi exception. This used to work for us as well and now both vmc-bindings-1.9.0.jar and vmc-bindings-1.6.0.jar fail the same way. Must be a recent regression.

Python seems to be failing on "updated" field in a similar way. It seems like the schema changed, but the java and python libs were not updated.

**Comment by jobingeo** [comment] 2019-07-24 11:43
Yes. There is an issue. We are looking into it.

**Comment by dhci** [comment] 2019-07-25 15:01
> Yes. There is an issue. We are looking into it.

Thank you, @jobingeo. Do you, guys, have ETA for the updated vmc-bindings.jar? We are blocked on this.

We are a VMC/VMware partner. Would it help if we engage our partnerships channels? All our QA and development is currently blocked because of this recent regression. Thank you!

**Comment by jobingeo** [comment] 2019-07-26 17:10
ETA for updated bindings availability - 08/01.

**Comment by dhci** [comment] 2019-07-26 20:55
Great. Thank you very much, @jobingeo!

**Comment by jobingeo** [comment] 2019-08-01 04:01
Updated ETA : 08/08/19.  There are some changes required in VMC Backend as well. This should be available next week.

**Comment by dhci** [comment] 2019-08-01 17:36
@jobingeo any chance you can publish a fix for this specific problem earlier than 8/8? All our development and QA is stuck for weeks because of this.

In the future, would it be possible to preserver server API compatibility? We are going into production soon and such incompatible server API changes will take down our services and our customers. Thanks!

**Comment by jobingeo** [comment] 2019-08-02 10:37
@dhci We will try our best for an early push. VMC Engineering is looking into this.
Can you also engage your partnership channels?

**Comment by jobingeo** [comment] 2019-08-07 03:27
@dhci  @datvmc 
Can you please retry your use case now? The backend fix for this issue is available now

**Comment by dhci** [comment] 2019-08-08 01:52
> @dhci @datvmc
> Can you please retry your use case now? The backend fix for this issue is available now

@joningeo The server side fix worked for us! Thanks a lot for your help.

**Closed** 2019-08-08 01:57 UTC
